services:
  crm_back:
    build: .
    container_name: my_crm
    restart: always
    depends_on:
      - crm_db
    env_file:
      - .env
    ports:
      - "8001:8000"
    volumes:
      - ./app:/app

  crm_db:
    image: postgres:15
    container_name: crm_postgres
    env_file:
      - .env
    ports:
      - "5434:5432"
    volumes:
      - crm_data:/var/lib/postgresql/data

volumes:
  crm_data:
