services:
  crm_back:
    build: .
    container_name: my_crm_dev
    restart: always
    depends_on:
      - crm_db_dev
    env_file:
      - .env.dev
    ports:
      - "8002:8000"
    volumes:
      - ./app:/app
    

  crm_db_dev:
    image: postgres:15
    container_name: crm_postgres_dev
    env_file:
      - .env.dev
    ports:
      - "5433:5432"
    volumes:
      - crm_data:/var/lib/postgresql/data

volumes:
  crm_data:
